name: Docker Package and Push
description: "Package and Push"

inputs:
  image-name:
    description: 'The base name for the Docker image (e.g., owner/repo)'
    required: true
  docker-context:
    description: 'The build context for Docker (default: .)'
    required: false
    default: '.'
  sha:
    description: 'The Git SHA to use for tagging'
    required: true
  github-token:
    description: 'The GITHUB_TOKEN for authentication'
    required: true
  github-actor:
    description: 'The user who triggered the workflow (github.actor)'
    required: true

runs: 
  using: 'composite'
  steps:
  - name: Login to GitHub Container Registry
    uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ inputs.github-token }}

  - name: Build and push Docker image
    uses: docker/build-push-action@v5
    with:
      context: ${{ inputs.docker-context }}
      push: true
      tags: |
        ghcr.io/${{ inputs.image-name }}:latest
        ghcr.io/${{ inputs.image-name }}:${{ inputs.sha }}