name: Next.JS PR CI

on:
 workflow_call:
  inputs:
    node-version:
      description: 'The Go version to use'
      required: true
      type: string
    image-name:
      description: 'The base name for the Docker image (e.g., owner/repo)'
      required: true
      type: string
    docker-context:
      description: 'The build context for Docker (default: .)'
      required: false
      type: string
      default: '.'
    sha:
      description: 'The Git SHA to use for tagging'
      required: true
      type: string

  secrets:
    github-token:
      description: 'The GITHUB_TOKEN for authentication'
      required: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    outputs:
      artifact-name: ${{steps.set-artifact-name.outputs.name}}

    steps:
    ### BUILD 
    - uses: actions/checkout@v4
  
    - name: Set up Environment
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: |
        export PNPM_HOME="/pnpm";
        export PATH="$PNPM_HOME:$PATH";
        corepack enable pnpm && pnpm i --frozen-lockfile; 
      
    - name: Build
      run: pnpm run build;

    - name: Prepare artifact for Docker
      run: |
        mkdir -p app/.next
        cp -r public app/
        cp -r .next/standalone app/.next/
        cp -r .next/static app/.next/

    - name: Set Artifact name
      id: set-artifact-name
      run: echo "name=app-${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{steps.set-artifact-name.outputs.name}}
        retention-days: 1
        path: ./app

    ### TEST

  ### PACKAGE
  package:
    runs-on: ubuntu-latest
    name: Export Docker Image

    needs: build
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{needs.build.outputs.artifact-name}}

    - name: Package and Push Image    
      uses: high-effort-low-stress/workflows/actions/docker-package@main
      with:
        image-name: ghcr.io/${{ github.repository }}
        sha: ${{ github.sha }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-actor: ${{ github.actor }}